services:
  # База данных
  postgres:
    image: postgres:15-alpine
    container_name: lab5-postgres
    environment:
      POSTGRES_DB: lab5_db
      POSTGRES_USER: lab5_user
      POSTGRES_PASSWORD: lab5_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab5_user -d lab5_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Наше приложение
  app:
    build: .  # Собираем из Dockerfile
    container_name: lab5-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab5_db
      SPRING_DATASOURCE_USERNAME: lab5_user
      SPRING_DATASOURCE_PASSWORD: lab5_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres_data: